name: meworld
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_riverpod: ^1.0.4
  go_router: ^4.3.0
  email_validator: ^2.1.17
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  password_validated_field: ^0.0.3
  flutter_rating_bar: ^4.0.1
  get_it: ^7.2.0
  firebase_core: ^1.22.0
  cloud_functions: ^3.3.7
  firebase_auth: ^3.8.0
  cloud_firestore: ^3.4.7
  flutter_datetime_picker: ^1.5.1
  syncfusion_flutter_datepicker: ^20.2.48
  image_picker: ^0.8.5+3
  toggle_switch: ^2.0.1
  group_button: ^5.2.0
  time_range_picker: ^2.2.0
  freezed_annotation: ^2.1.0
  json_annotation: ^4.6.0
  uuid: ^3.0.6
  flutter_time_range: ^0.0.2
  algolia: ^1.1.1
  agora_rtc_engine: ^5.3.0
  permission_handler: ^10.0.0
  permission_handler_web: ^0.0.2
  google_maps_flutter: ^2.2.0
  google_maps_flutter_web: ^0.4.0+2
  flutter_polyline_points: ^1.0.0
  flutter_svg: ^1.1.5
  location: ^4.4.0
  dio: ^4.0.6
  random_string: ^2.3.1
  crypto: ^3.0.2
  convert: ^3.0.2
  flex_color_scheme: ^5.1.0
  google_fonts: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  # hive_generator: ^[version]
  # build_runner: ^[version]
  flutter_lints: ^2.0.0
  build_runner: ^2.2.1
  freezed: ^2.1.0+1
  json_serializable: ^6.3.2
flutter:
  uses-material-design: true
  assets:
    - assets/images/
