// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBntzbM2WW4WEw8LgPnwuCCiFLzTpaWEPs',
    appId: '1:334513007663:web:a34c90d9a637826be26ada',
    messagingSenderId: '334513007663',
    projectId: 'meworld-329f3',
    authDomain: 'meworld-329f3.firebaseapp.com',
    databaseURL: 'https://meworld-329f3-default-rtdb.firebaseio.com',
    storageBucket: 'meworld-329f3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASzlIsSdNYvKFCnoE6RzXgHhRv-kJriDg',
    appId: '1:334513007663:android:c9b6faee8e6f3b9de26ada',
    messagingSenderId: '334513007663',
    projectId: 'meworld-329f3',
    databaseURL: 'https://meworld-329f3-default-rtdb.firebaseio.com',
    storageBucket: 'meworld-329f3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5OMkfHwM0G8D6COH9Tc6AYQQzO5KgYaQ',
    appId: '1:334513007663:ios:6feb9fb702650392e26ada',
    messagingSenderId: '334513007663',
    projectId: 'meworld-329f3',
    databaseURL: 'https://meworld-329f3-default-rtdb.firebaseio.com',
    storageBucket: 'meworld-329f3.appspot.com',
    iosClientId: '334513007663-geg2hlg77srh9tjuuq0iadlu2gdvsu5i.apps.googleusercontent.com',
    iosBundleId: 'com.example.meworld',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5OMkfHwM0G8D6COH9Tc6AYQQzO5KgYaQ',
    appId: '1:334513007663:ios:6feb9fb702650392e26ada',
    messagingSenderId: '334513007663',
    projectId: 'meworld-329f3',
    databaseURL: 'https://meworld-329f3-default-rtdb.firebaseio.com',
    storageBucket: 'meworld-329f3.appspot.com',
    iosClientId: '334513007663-geg2hlg77srh9tjuuq0iadlu2gdvsu5i.apps.googleusercontent.com',
    iosBundleId: 'com.example.meworld',
  );
}
